import tkinter
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
import pymysql 
t=tkinter.Tk()
t.geometry('800x800')
def storesavescreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    def checkdata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select count(*) from store where storeid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        if data[0]==0:
            messagebox.showinfo('Hi','OK pls go ahead')
        else:
            messagebox.showerror('Hi','You cannot enter')        
        db.close()
    def savedata():
        if len(aa.get())==0 or len(bb.get())==0 or len(cc.get())==0 or len(dd.get())==0 or len(ee.get())==0 or len(ff.get())==0 or len(gg.get())==0:
            messagebox.showerror('hi','Please fill all data')
        else:
            xa=int(aa.get())
            xb=bb.get()
            xc=cc.get()
            xd=dd.get()
            xe=ee.get()
            xf=ff.get()
            xg=gg.get()
            db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
            cur=db.cursor()
            sql="insert into store values(%d,'%s','%s','%s','%s','%s','%s')"%(xa,xb,xc,xd,xe,xf,xg) 
            cur.execute(sql)
            db.commit()
            db.close()
            messagebox.showinfo('Hi','Saved')
            aa.delete(0,100)
            bb.delete(0,100)
            cc.delete(0,100)
            dd.delete(0,100)
            ee.delete(0,100)
            ff.delete(0,100)
            gg.delete(0,100)
    def close():
        t.destroy()
        
    a=Label(c2,text='STORE ID',font=('times new roman bold',13))
    a.place(x=100,y=100)
    aa=Entry(c2,width=30,font=('times new roman',12))
    aa.place(x=275,y=100)
    btf=Button(c2,text='CHECK',font=('times new roman bold',11),bg='orange',command=checkdata)
    btf.place(x=540,y=100)
    b=Label(c2,text='NAME',font=('times new roman bold',13))
    b.place(x=100,y=150)
    bb=Entry(c2,width=30,font=('times new roman',12))
    bb.place(x=275,y=150)
    c=Label(c2,text='ADDRESS',font=('times new roman bold',13))
    c.place(x=100,y=200)
    cc=Entry(c2,width=30,font=('times new roman',12))
    cc.place(x=275,y=200)
    d=Label(c2,text='CITY',font=('times new roman bold',13))
    d.place(x=100,y=250)
    dd=Entry(c2,width=30,font=('times new roman',12))
    dd.place(x=275,y=250)
    e=Label(c2,text='EMAIL',font=('times new roman bold',13))
    e.place(x=100,y=300)
    ee=Entry(c2,width=30,font=('times new roman',12))
    ee.place(x=275,y=300)
    f=Label(c2,text='PHONE NO.',font=('times new roman bold',13))
    f.place(x=100,y=350)
    ff=Entry(c2,width=30,font=('times new roman',12))
    ff.place(x=275,y=350)
    g=Label(c2,text='REGISTRATION NO.',font=('times new roman bold',13))
    g.place(x=100,y=400)
    gg=Entry(c2,width=30,font=('times new roman',12))
    gg.place(x=275,y=400)
    h=Button(c2,text='SAVE',font=('times new roman bold',11),fg='white',bg='green',command=savedata)
    h.place(x=305,y=450)
    j=Button(c2,text='CLOSE',font=('times new roman bold',11),fg='white',bg='purple',command=close)
    j.place(x=385,y=450)

def storedeletescreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    xt=[]
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select storeid from store"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xt.append(res[0])
        db.close()
        
    def delete():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="delete from store where storeid=%d"%(xa)
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo('Hi','Deleted')    
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
    def close():
        t.destroy()
    a=Label(c2,text='STOCK ID',font=('times new roman bold',13))
    a.place(x=100,y=100)
    aa=ttk.Combobox(c2,font=('times new roman',12))
    aa.place(x=200,y=100)
    filldata()
    aa['values']=xt
    h=Button(c2,text='DELETE',font=('times new roman bold',11),bg='red',command=delete)
    h.place(x=200,y=200)
    j=Button(c2,text='CLOSE',font=('times new roman bold',11),fg='white',bg='purple',command=close)
    j.place(x=315,y=200)

def storeupdatescreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    def close():
        t.destroy()
    xt=[]
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select storeid from store"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xt.append(res[0])
        db.close()
    def finddata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select name,address,city,email,phone,regisno from store where storeid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
        bb.insert(0,data[0])
        cc.insert(0,data[1])
        dd.insert(0,data[2])
        ee.insert(0,data[3])
        ff.insert(0,data[4])
        gg.insert(0,data[5])
        db.close()
    def updatedata():
        xa=int(aa.get())
        xb=bb.get()
        xc=cc.get()
        xd=dd.get()
        xe=ee.get()
        xf=ff.get()
        xg=gg.get()
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="update store set name='%s',address='%s',city='%s',email='%s',phone='%s',regisno='%s' where storeid=%d"%(xb,xc,xd,xe,xf,xg,xa)
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo('hi','updated')
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
    
    a=Label(c2,text='STORE ID',font=('times new roman bold',12),bg='pink')
    a.place(x=100,y=100)
    aa=ttk.Combobox(t,width=37)
    aa.place(x=350,y=100)
    filldata()
    aa['values']=xt
    b1=Button(c2,text='FIND',command=finddata,width=8,font=('times new roman bold',12),bg='orange')
    b1.place(x=450,y=100)
    b=Label(c2,text='NAME',font=('times new roman bold',13),bg='pink')
    b.place(x=100,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=200,y=150)
    c=Label(c2,text='ADDRESS',font=('times new roman bold',13),bg='pink')
    c.place(x=100,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=200,y=200)
    d=Label(c2,text='CITY',font=('times new roman bold',13),bg='pink')
    d.place(x=100,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=200,y=250)
    e=Label(c2,text='EMAIL',font=('times new roman bold',13),bg='pink')
    e.place(x=100,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=200,y=300)
    f=Label(c2,text='PHONE',font=('times new roman bold',13),bg='pink')
    f.place(x=100,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=200,y=350)
    g=Label(c2,text='REGIST.No',font=('times new roman bold',13),bg='pink')
    g.place(x=100,y=400)
    gg=Entry(c2,width=40)
    gg.place(x=200,y=400)
    h=Button(c2,text='UPDATE',font=('times new roman bold',11),fg='white',bg='blue',command=updatedata)
    h.place(x=150,y=450)
    j=Button(c2,text='CLOSE',font=('times new roman bold',11),fg='white',bg='purple',command=close)
    j.place(x=250,y=450)    

def storefindscreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)

    def new():
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
    
    def close():
        t.destroy()
    xt=[]
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select storeid from store"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xt.append(res[0])
        db.close()
    def finddata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select name,address,city,email,phone,regisno from store where storeid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
        bb.insert(0,data[0])
        cc.insert(0,data[1])
        dd.insert(0,data[2])
        ee.insert(0,data[3])
        ff.insert(0,data[4])
        gg.insert(0,data[5])
        db.close()
  
    a=Label(c2,text='STORE ID',font=('times new roman bold',12),bg='pink')
    a.place(x=100,y=100)
    aa=ttk.Combobox(t,width=37)
    aa.place(x=350,y=100)
    filldata()
    aa['values']=xt
    b1=Button(c2,text='FIND',command=finddata,width=8,font=('times new roman bold',11),bg='orange')
    b1.place(x=450,y=100)
    b=Label(c2,text='NAME',font=('times new roman bold',13),bg='pink')
    b.place(x=100,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=200,y=150)
    c=Label(c2,text='ADDRESS',font=('times new roman bold',13),bg='pink')
    c.place(x=100,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=200,y=200)
    d=Label(c2,text='CITY',font=('times new roman bold',13),bg='pink')
    d.place(x=100,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=200,y=250)
    e=Label(c2,text='EMAIL',font=('times new roman bold',13),bg='pink')
    e.place(x=100,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=200,y=300)
    f=Label(c2,text='PHONE',font=('times new roman bold',13),bg='pink')
    f.place(x=100,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=200,y=350)
    g=Label(c2,text='REGIST.No',font=('times new roman bold',13),bg='pink')
    g.place(x=100,y=400)
    gg=Entry(c2,width=40)
    gg.place(x=200,y=400)
    h=Button(c2,text='NEW',font=('times new roman bold',11),fg='white',bg='orange',command=new)
    h.place(x=150,y=450)
    j=Button(c2,text='CLOSE',font=('times new roman bold',11),fg='white',bg='purple',command=close)
    j.place(x=250,y=450)    

def storeshowscreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    xa=[]
    xb=[]
    xc=[]
    xd=[]
    xe=[]
    xf=[]
    xg=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select storeid,name,address,city,email,phone,regisno from store"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xa.append(res[0])
            xb.append(res[1])
            xc.append(res[2])
            xd.append(res[3])
            xe.append(res[4])
            xf.append(res[5])
            xg.append(res[6])
        db.close()
    def firstdata():
        global i
        i=0
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
        gg.insert(0, xg[i])
    def nextdata():
        global i
        i=i+1
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
        gg.insert(0, xg[i])
    def prevdata():
        global i
        i=i-1
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
        gg.insert(0, xg[i])
    def lastdata():
        global i
        i=len(xa)-1
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        gg.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
        gg.insert(0, xg[i])
   
    a=Label(c2,text='STORE ID',font=('times new roman bold',12),fg='black',bg='pink')
    a.place(x=100,y=100)
    aa=Entry(c2,width=40)
    aa.place(x=200,y=100)
    btf=Button(c2,text='FIRST',command=firstdata,width=8,font=('times new roman bold',12),fg='white', bg='orange')
    btf.place(x=120,y=450)
    b=Label(c2,text='NAME',font=('times new roman bold',12),fg='black',bg='pink')
    b.place(x=100,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=200,y=150)
    c=Label(c2,text='ADDRESS',font=('times new roman bold',12),fg='black',bg='pink')
    c.place(x=100,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=200,y=200)
    d=Label(c2,text='CITY',font=('times new roman bold',12),fg='black',bg='pink')
    d.place(x=100,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=200,y=250)
    e=Label(c2,text='EMAIL',font=('times new roman bold',12),fg='black',bg='pink')
    e.place(x=100,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=200,y=300)
    f=Label(c2,text='PHONE',font=('times new roman bold',12),fg='black',bg='pink')
    f.place(x=100,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=200,y=350)
    g=Label(c2,text='REGIST.No',font=('times new roman bold',12),fg='black',bg='pink')
    g.place(x=100,y=400)
    gg=Entry(c2,width=40)
    gg.place(x=200,y=400)
    h=Button(c2,text='NEXT',command=nextdata,width=8,font=('times new roman bold',12),fg='white', bg='green')
    h.place(x=220,y=450)
    j=Button(c2,text='PREV',command=prevdata,width=8,font=('times new roman bold',12),fg='white', bg='red')
    j.place(x=320,y=450)
    k=Button(c2,text='LAST',command=lastdata,width=8,font=('times new roman bold',12),fg='white', bg='blue')
    k.place(x=420,y=450)
    filldata()

def productsavescreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    def checkdata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select count(*) from products where productid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        if data[0]==0:
            messagebox.showinfo('Hi','OK pls go ahead')
        else:
            messagebox.showerror('Hi','You cannot enter')        
        db.close()
    def savedata():
        if len(aa.get())==0 or len(bb.get())==0 or len(cc.get())==0 or len(dd.get())==0 or len(ee.get())==0 or len(ff.get())==0:
            messagebox.showerror('hi','Please fill all data')
        else:
            xa=int(aa.get())
            xb=int(bb.get())
            xc=cc.get()
            xd=int(dd.get())
            xe=int(ee.get())
            xf=int(ff.get())
            db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
            cur=db.cursor()
            sql="insert into products values(%d,'%d','%s','%d','%d','%d')"%(xa,xb,xc,xd,xe,xf) 
            cur.execute(sql)
            db.commit()
            db.close()
            messagebox.showinfo('Hi','Saved')
            aa.delete(0,100)
            bb.delete(0,100)
            cc.delete(0,100)
            dd.delete(0,100)
            ee.delete(0,100)
            ff.delete(0,100)
    def close():
        t.destroy()
    
    
    a=Label(c2,text='PRODUCT ID',font=('times new roman bold',12),fg='black',bg='pink')
    a.place(x=100,y=100)
    aa=Entry(c2,width=40)
    aa.place(x=210,y=100)
    b=Label(c2,text='PCAT ID',font=('times new roman bold',12),fg='black',bg='pink')
    b.place(x=100,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=210,y=150)
    c=Label(c2,text='PNAME',font=('times new roman bold',12),fg='black',bg='pink')
    c.place(x=100,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=210,y=200)
    d=Label(c2,text='PRICE PER UNIT',font=('times new roman bold',10),fg='black',bg='pink')
    d.place(x=100,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=210,y=250)
    e=Label(c2,text='OPEN Qty',font=('times new roman bold',12),fg='black',bg='pink')
    e.place(x=100,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=210,y=300)
    f=Label(c2,text='CURRENT Qty',font=('times new roman bold',12),fg='black',bg='pink')
    f.place(x=100,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=210,y=350)
    b1=Button(c2,text='SAVE',command=savedata,width=8,font=('times new roman bold',12),fg='white',bg='green')
    b1.place(x=250,y=400)
    b2=Button(c2,text='CLOSE',command=close,width=8,font=('times new roman bold',12),fg='white',bg='purple')
    b2.place(x=350,y=400)
    
    b2=Button(c2,text='CHECK',command=checkdata,width=8,font=('times new roman bold',12),bg='orange')
    b2.place(x=460,y=100)

def productdeletescreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    xt=[]
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select custid from customers"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xt.append(res[0])
        db.close()
    def deletedata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')#common step
        cur=db.cursor()#common step
        sql="delete from products where productid=%d" %(xa) 
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo('Hi','deleted')
        aa.delete(0,100)
    def close():
        t.destroy()
    a=Label(c2,text='PRODUCT ID',font=('times new roman bold',12),bg='pink')
    a.place(x=90,y=100)
    aa=ttk.Combobox(t,width=37)
    aa.place(x=350,y=100)
    filldata()
    aa['values']=xt
    b1=Button(c2,text='DELETE',command=deletedata,width=8,font=('times new roman bold',12),fg='white',bg='red')
    b1.place(x=200,y=150)
    b2=Button(c2,text='CLOSE',command=close,width=8,font=('times new roman bold',12),fg='white',bg='purple')
    b2.place(x=300,y=150)
def productupdatescreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    xt=[]
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select productid from products"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xt.append(res[0])
        db.close()
    def finddata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select pcatid,pname,priceperunit,openqty,currqty from products where productid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        bb.insert(0,data[0])
        cc.insert(0,data[1])
        dd.insert(0,data[2])
        ee.insert(0,data[3])
        ff.insert(0,data[4])
        db.close()
    def updatedata():
        xa=int(aa.get())
        xb=int(bb.get())
        xc=cc.get()
        xd=int(dd.get())
        xe=int(ee.get())
        xf=int(ff.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="update products set pcatid='%d',pname='%s',priceperunit='%d',openqty='%d',currqty='%d' where productid=%d"%(xb,xc,xd,xe,xf,xa)
        cur.execute(sql)
        db.commit()
        db.close()
        messagebox.showinfo('hi','updated')
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100) 
    
    def close():
        t.destroy()
  
    a=Label(c2,text='PRODUCT ID',font=('times new roman bold',12),bg='pink')
    a.place(x=80,y=100)
    aa=ttk.Combobox(t,width=36)
    aa.place(x=332,y=100)
    filldata()
    aa['values']=xt
    b1=Button(c2,text='FIND',command=finddata,width=8,font=('times new roman bold',12),bg='orange')
    b1.place(x=430,y=100)
    b=Label(c2,text='PCAT ID',font=('times new roman bold',12),bg='pink')
    b.place(x=80,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=180,y=150)
    c=Label(c2,text='PNAME',font=('times new roman bold',12),bg='pink')
    c.place(x=80,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=180,y=200)
    d=Label(c2,text='PRICE PER UNIT',font=('times new roman bold',10),bg='pink')
    d.place(x=80,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=180,y=250)
    e=Label(c2,text='OPEN Qty',font=('times new roman bold',12),bg='pink')
    e.place(x=80,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=180,y=300)
    f=Label(c2,text='CURRENT Qty',font=('times new roman bold',10),bg='pink')
    f.place(x=80,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=180,y=350)
    b2=Button(c2,text='UPDATE',command=updatedata,width=8,font=('times new roman bold',12),fg='white',bg='Blue')
    b2.place(x=200,y=400)
    b3=Button(c2,text='CLOSE',command=close,width=8, font=('times new roman bold',12),fg='white',bg='purple')
    b3.place(x=300,y=400)

def productfindscreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    xt=[]
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select productid from products"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xt.append(res[0])
        db.close()
    def finddata():
        xa=int(aa.get())
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select pcatid,pname,priceperunit,openqty,currqty from products where productid=%d"%(xa)
        cur.execute(sql)
        data=cur.fetchone()
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        bb.insert(0,data[0])
        cc.insert(0,data[1])
        dd.insert(0,data[2])
        ee.insert(0,data[3])
        ff.insert(0,data[4])
        db.close()
    def new():
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
    
    def close():
        t.destroy()
    
    a=Label(c2,text='PRODUCT ID',font=('times new roman bold',12),bg='pink')
    a.place(x=80,y=100)
    aa=ttk.Combobox(t,width=36)
    aa.place(x=332,y=100)
    filldata()
    aa['values']=xt
    b1=Button(c2,text='FIND',command=finddata,width=8,font=('times new roman bold',12),bg='orange')
    b1.place(x=430,y=100)
    b=Label(c2,text='PCAT ID',font=('times new roman bold',12),bg='pink')
    b.place(x=80,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=180,y=150)
    c=Label(c2,text='PNAME',font=('times new roman bold',12),bg='pink')
    c.place(x=80,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=180,y=200)
    d=Label(c2,text='PRICE PER UNIT',font=('times new roman bold',10),bg='pink')
    d.place(x=80,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=180,y=250)
    e=Label(c2,text='OPEN Qty',font=('times new roman bold',12),bg='pink')
    e.place(x=80,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=180,y=300)
    f=Label(c2,text='CURRENT Qty',font=('times new roman bold',10),bg='pink')
    f.place(x=80,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=180,y=350)
    b2=Button(c2,text='NEW',command=new,width=8,font=('times new roman bold',12),fg='white', bg='orange')
    b2.place(x=200,y=400)
    b3=Button(c2,text='CLOSE',command=close,width=8,font=('times new roman bold',12),fg='white', bg='purple')
    b3.place(x=300,y=400)

def productshowscreen():
    c2=Canvas(t,height=800,width=650,bg='pink')
    c2.place(x=150,y=0)
    xa=[]
    xb=[]
    xc=[]
    xd=[]
    xe=[]
    xf=[]
    i=0
    def filldata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='sms')
        cur=db.cursor()
        sql="select productid,pcatid,pname,priceperunit,openqty,currqty from products"
        cur.execute(sql)
        data=cur.fetchall()
        for res in data:
            xa.append(res[0])
            xb.append(res[1])
            xc.append(res[2])
            xd.append(res[3])
            xe.append(res[4])
            xf.append(res[5])
        db.close()
    def firstdata():
        global i
        i=0
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
    def nextdata():
        global i
        i=i+1
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
    def prevdata():
        global i
        i=i-1
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])
    def lastdata():
        global i
        i=len(xa)-1
        aa.delete(0,100)
        bb.delete(0,100)
        cc.delete(0,100)
        dd.delete(0,100)
        ee.delete(0,100)
        ff.delete(0,100)
        aa.insert(0, xa[i])
        bb.insert(0, xb[i])
        cc.insert(0, xc[i])
        dd.insert(0, xd[i])
        ee.insert(0, xe[i])
        ff.insert(0, xf[i])

    a=Label(c2,text='PRODUCT ID',font=('times new roman bold',12),bg='pink')
    a.place(x=80,y=100)
    aa=Entry(c2,width=40)
    aa.place(x=200,y=100)
    
    b=Label(c2,text='PCAT ID',font=('times new roman bold',12),bg='pink')
    b.place(x=80,y=150)
    bb=Entry(c2,width=40)
    bb.place(x=200,y=150)
    c=Label(c2,text='PNAME',font=('times new roman bold',12),bg='pink')
    c.place(x=80,y=200)
    cc=Entry(c2,width=40)
    cc.place(x=200,y=200)
    d=Label(c2,text='PRICE PER UNIT',font=('times new roman bold',10),bg='pink')
    d.place(x=80,y=250)
    dd=Entry(c2,width=40)
    dd.place(x=200,y=250)
    e=Label(c2,text='OPEN Qty',font=('times new roman bold',12),bg='pink')
    e.place(x=80,y=300)
    ee=Entry(c2,width=40)
    ee.place(x=200,y=300)
    f=Label(c2,text='CURRENT Qty',font=('times new roman bold',12),bg='pink')
    f.place(x=80,y=350)
    ff=Entry(c2,width=40)
    ff.place(x=200,y=350)
    
    b2=Button(c2,text='FIRST',command=firstdata,width=8,font=('times new roman bold',12),fg='white',bg='orange')
    b2.place(x=100,y=400)
    b3=Button(c2,text='NEXT',command=nextdata,width=8,font=('times new roman bold',12),fg='white',bg='green')
    b3.place(x=200,y=400)
    b4=Button(c2,text='PREV',command=prevdata,width=8,font=('times new roman bold',12),fg='white',bg='red')
    b4.place(x=300,y=400)
    b5=Button(c2,text='LAST',command=lastdata,width=8,font=('times new roman bold',12),fg='white',bg='blue')
    b5.place(x=400,y=400)
    filldata()    
    
    
c1=Canvas(t,height=800,width=150,bg='red')
c1.place(x=0,y=0)
c2=Canvas(t,height=800,width=650,bg='pink')
c2.place(x=150,y=0)
b1=Button(c1,text='StoreInsert',fg='White',bg='red',font=('arial',15),command=storesavescreen)
b1.place(x=10,y=10)
b2=Button(c1,text='StoreDelete',fg='White',bg='red',font=('arial',15),command=storedeletescreen)
b2.place(x=10,y=55)
b3=Button(c1,text='StoreUpdate',fg='White',bg='red',font=('arial',15),command=storeupdatescreen)
b3.place(x=10,y=100)
b4=Button(c1,text='StoreFind',fg='White',bg='red',font=('arial',15),command=storefindscreen)
b4.place(x=10,y=145)
b5=Button(c1,text='StoreShow',fg='White',bg='red',font=('arial',15),command=storeshowscreen)
b5.place(x=10,y=190)
b6=Button(c1,text='ProductInsert',fg='White',bg='red',font=('arial',15),command=productsavescreen)
b6.place(x=10,y=300)
b7=Button(c1,text='ProductDelete',fg='White',bg='red',font=('arial',15),command=productdeletescreen)
b7.place(x=10,y=350)
b8=Button(c1,text='ProductUpdate',fg='White',bg='red',font=('arial',15),command=productupdatescreen)
b8.place(x=10,y=400)
b9=Button(c1,text='ProductFind',fg='White',bg='red',font=('arial',15),command=productfindscreen)
b9.place(x=10,y=450)
b10=Button(c1,text='ProductShow',fg='White',bg='red',font=('arial',15),command=productshowscreen)
b10.place(x=10,y=500)
t.mainloop()