import tkinter 
from tkinter import*
from tkinter import ttk
#screen create 
t=tkinter.Tk()
#size
t.geometry('800x800')
#title of screen
t.title('New Text Document-Notepad')
mb=Menu()
fm=Menu()
em=Menu()
fo=Menu()
vi=Menu()
hp=Menu()
fm.add_command(label='New     Ctrl+N')
fm.add_separator()
fm.add_command(label='New Window   Ctrl+shift+N')
fm.add_separator()
fm.add_command(label='Open..   Ctrl+O')
fm.add_separator()
fm.add_command(label='Save     Ctrl+S')
fm.add_separator()
fm.add_command(label='Save As    Ctrl+Shift+S')
fm.add_separator()
fm.add_command(label='Page Setup...')
fm.add_separator()
fm.add_command(label='Print    Ctrl+P')
fm.add_separator()
fm.add_command(label='Exit')
fm.add_separator()
mb.add_cascade(label='File',menu=fm)
em.add_command(label='Undo    Ctrl+Z')
em.add_separator()
em.add_command(label='Cut    Ctrl+X')
em.add_separator()
em.add_command(label='Copy    Ctrl+C')
em.add_separator()
em.add_command(label='Paste     Ctrl+V')
em.add_separator()
em.add_command(label='Delete   Del')
em.add_separator()
em.add_command(label='Search with bieng...  Crtl+E')
em.add_separator()
em.add_command(label='Find    Ctrl+F')
em.add_separator()
em.add_command(label='Find Next   F3')
em.add_separator()
em.add_command(label='Find Previous  Shift+F3')
em.add_separator()
em.add_command(label='Replace    Crtl+H')
em.add_separator()
em.add_command(label='Go    Crtl+G')
em.add_separator()
em.add_command(label='Select All    Crtl+A')
em.add_separator()
em.add_command(label='Time/Date    F5')
em.add_separator()
mb.add_cascade(label='Edit',menu=em)
fo.add_command(label='Word Wrap')
fo.add_separator()
fo.add_command(label='Font..')
fo.add_separator()
mb.add_cascade(label='Format',menu=fo)
vi.add_command(label='Zoom   >')
vi.add_separator()
vi.add_command(label='Status Bar')
vi.add_separator()
mb.add_cascade(label='View',menu=vi)
hp.add_command(label='View Help')
hp.add_separator()
hp.add_command(label='Send Feedback')
hp.add_separator()
hp.add_command(label='About Notepad')
hp.add_separator()
mb.add_cascade(label='Help',menu=hp)
t.config(menu=mb)

t.mainloop()