import tkinter 
from tkinter import*
from tkinter import ttk
#screen create 
t=tkinter.Tk()
#size
t.geometry('800x800')
#title of screen
t.title('my first screen')
a=Label(t,text='Registration Form')
a.place(x=300,y=20)
b=Label(t,text='Name')
b.place(x=50,y=60)
d=Entry(t,width=20)
d.place(x=400,y=60)
e=Label(t,text='Passward')
e.place(x=50,y=100)
f=Entry(t,width=20,show='*')
f.place(x=400,y=100)
g=Label(t,text='Qualification')
g.place(x=50,y=140)
h=Listbox(t,height=4)
h.insert(1,'MCA')
h.insert(2,'BCA')
h.insert(3,'MBA')
h.insert(4,'MA')
h.place(x=400,y=140)
m=Label(t,text='Age')
m.place(x=50,y=210)
sp=Spinbox(t,from_=18,to=60)
sp.place(x=400,y=210)
h=Label(t,text='Score')
h.place(x=50,y=250)
sc=Scale(t,from_=1, to=100, orient=HORIZONTAL)
sc.place(x=400,y=250)
nn=Label(t,text='Sex')
nn.place(x=50,y=300)
xp=IntVar()
rm=Radiobutton(t,text='Male',variable=xp,value=1)
rf=Radiobutton(t,text='Female',variable=xp,value=0)
rm.place(x=400,y=300)
rf.place(x=500,y=300)
r=Label(t,text='Hobbies')
r.place(x=50,y=350)
cr=IntVar()
cm=IntVar()
hr=Checkbutton(t,text='Ready',variable=cr,onvalue=1,offvalue=0)
hm=Checkbutton(t,text='Music',variable=cm,onvalue=1,offvalue=0)
hr.place(x=400,y=350)
hm.place(x=500,y=350)
s=Label(t,text='City')
s.place(x=50,y=400)
cb=ttk.Combobox(t)
cb['values']=['Chennai','Delhi','Noida']
cb.place(x=400,y=400)
pr=ttk.Progressbar(t)
pr['value']=50
pr.place(x=400,y=450)
b1=Button(t,text='Save')
b1.place(x=200,y=600)
b2=Button(t,text='Cancel')
b2.place(x=300,y=600)
t.config(bg='skyblue')

t.mainloop()